apiVersion: v1
kind: Service
metadata:
  name: {{ include "locust-chart.fullname" . }}
  labels:
    {{- include "locust-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.locust.webui_port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.worker.enabled }}
    - port: {{ .Values.locust.cluster_port }}
      targetPort: cluster
      protocol: TCP
      name: cluster
    {{- end }}
  selector:
    {{- include "locust-chart.selectorLabels" . | nindent 4 }}
{{- if .Values.worker.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "locust-chart.fullname" . }}-worker-headless
  labels:
    {{- include "locust-chart.worker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "locust-chart.worker.selectorLabels" . | nindent 4 }}
{{- end }}
